// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SamplePayload.proto

package com.my.protoproject.proto;

public interface SamplePayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SomeProto.SamplePayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
